spring:
  application:
    name: alsorg-packing

  profiles:
    active: staging   # DEFAULT â†’ change only on prod server

server:
  port: 8080

# =====================
# COMMON JPA SETTINGS
# =====================
spring.jpa:
  open-in-view: false
  properties:
    hibernate:
      format_sql: true

# =====================
# LOGGING
# =====================
logging:
  level:
    root: INFO
    com.alsorg: DEBUG
